[package]
name = "poc-tokio-messaging"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.32.0", features = [
    "sync",
    "macros",
    "rt-multi-thread",
    "time"
    ]}
